title: Stackbit Event Theme
baseURL: /
params:
  layout_type: full-width
  style: classic
  palette: red
  mode: light
  base_font: sans-serif
  header:
    title: Event
    logo: images/logo.svg
    logo_alt: Event logo
    has_primary_nav: false
    has_secondary_nav: true
    secondary_nav_links:
      - label: About
        url: /about
        style: link
      - label: Sponsorship
        url: /sponsorship
        style: link
      - label: Committee
        url: '#'
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        no_follow: false
        type: action
      - label: Call for Papers
        url: thank-you
        style: primary
    has_anncmnt: false
  footer:
    has_primary_nav: false
    has_secondary_nav: false
    has_tertiary_nav: false
    has_social: false
    content: >-
      © Vardhaman College of Engineering. All rights reserved. This site was
      created with HUGO and Stackbit, by CSE Department.
  domain: 'https://aihpc-2-8e59b.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
